### ISSUE TITLE
[JS] Implement webpack build process

### ISSUE THREAD

**Issue by maltezacharias** [match4everyone/match4everything#17]
**Topic:**
Implement webpack building process for javascript ressources

**Relevant issues:**

**Further description:**
Separates JS, CSS and used resources from the django backend. Provides the infrastructure for possible future integrations of modern javascript, e.g. Vue.js

**Alternative approaches that could be considered:**
Manually keep everything together and despair

**Todos**
- [X] Integrate into build process (travis)
- [x] Pre-commit hook for building/linting the JS
- [x] Clean-Up Changes
