### ISSUE TITLE
Refactor the color scheme

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#3]
It feels like the template colors are everywhere in the css, directly in the svgs ... magic numbers everywhere.

## Todo
- find a new color config file json/css.. whatever fits to be put into `match4everyone/config`
- with 2-5 base colors that are sparsely used EVERYWHERE to emphasise the two participants
- and try to integrate them into existing templates (especially map, home)

## Resources
- [Color schemes with five colors ](https://color.adobe.com/search?q=dual)

![image](https://user-images.githubusercontent.com/8030048/83250269-270d9280-a1a8-11ea-89ad-5f2606549ed1.png)

**Comment by bjrne** [comment]
So lets use the 1st & 3rd for one color and 4th & 5th for the other? I think 2&3 are lacking contrast. According to this tool, this selection should also be quite accessible in terms of distinction and contrast: https://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by bjrne** [comment]
First color is #B35A0F

**Comment by feeds** [comment]
But I think the colors are not really pretty... its just the first one that appear when I put `dual` into the kuler search box haha.

**Comment by feeds** [comment]
Can this also be achieved with the cms? @Baschdl

**Comment by bjrne** [comment]
Would be even better, but if not, they can be set as variables and compiled into our custom bootstrap css code with the js refactoring @maltezacharias is working on right now :)

**Comment by Baschdl** [comment]
I don't see a possibility right now how we could integrate it into django-cms. I would integrate it into our configuration object.

**Comment by maltezacharias** [comment]
> I don't see a possibility right now how we could integrate it into django-cms. I would integrate it into our configuration object.

This would probably be problematic to read during the css and js build process. Does it have to be known in python? CSS files will be generated by webpack from the bootstrap scss which supports a concept of "theme colors" that can be set and overwritten before the CSS is generated.

**Comment by bjrne** [comment]
My personal todo list, since this will be several PRs:

- [x] correctly compile and include scss files with variables
- [x] use scss variables for all hardcoded style colors, apart from background colors and inline style blocks
- [x] replace btn blue with btn btn-primary

- [ ] styles aus htmls raus
- [ ] nach rgba suchen und ggf ersetzen durch vars
- [ ] wie machen wir Farben in password_set_email.html modular
- [ ] unify slightly varying background colors and use scss vars
- [ ] clean css structure further
